[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[project]
name = "model-components"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tarun Krisha", email = "krishnatarun7@gmail.com" }
]
requires-python = ">=3.11"

dependencies = [
    "dacite>=1.9.2",
    "datasets>=5.0.1",
    "mlflow>=3.16.0",
    "numpy<2",
    "tokenizers>=0.23.2",
    "torch==2.2.2",
    "torchvision==0.17.2",
    "transformers",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "D", "ARG"]
ignore = ["D415", "D100"]

[tool.ruff.lint.pydocstyle]
# Options: "google", "numpy", or "pep257"
convention = "google" 

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["ALL"]

[dependency-groups]
dev = [
    "bpython>=0.26",
    "pre-commit>=4.6.2",
    "ruff>=0.16.7",
]
