data:
    # train_val_split:
    # tokenizer_dir: "dataset_artifacts/gpt"
    seq_len: 100
    stride: 50

model:
    model_type: "GPTstyle"
    d_model: 32
    dff: 128
    num_heads: 8
    dec_num_layers: 3
    dropout: 0.1
    resume_from: output/checkpoints/GPTstyle/model.pt

inference:
    batch_size: 1
    max_new_tokens: 50
    # context_size: 100 #max_seq_len
    sampling_strategy: "top_k"
    top_k : 3
    temperature: 0.2