data:
    # train_val_split:
    tokenizer_dir: "dataset_artifacts/translation"

model:
    model_type: "Seq2Seq"
    d_model: 64
    dff: 256
    num_heads: 8
    seq_len: 100
    enc_num_layers: 2
    dec_num_layers: 1
    dropout: 0.1

training:

    batch_size: 64
    num_epochs: 10
    learning_rate: 0.001